# Generated by Django 6.0 on 2026-02-16 21:20

import django.db.models.deletion
import image_pro.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(upload_to='images/originals/')),
                ('processed_image', models.ImageField(blank=True, null=True, upload_to='images/processed/')),
                ('image_format', models.CharField(choices=[('jpg', 'JPEG'), ('png', 'PNG'), ('webp', 'WebP')], default='jpg', max_length=4)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=image_pro.models.default_expiry)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImageOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('resize', 'Resize'), ('convert', 'Convert'), ('filter', 'Filter')], default='resize', max_length=20)),
                ('parameters', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='image_pro.image')),
            ],
        ),
    ]
