# Generated by Django 6.0 on 2026-02-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_pro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='estimated_ready_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='processing_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
