# Generated by Django 6.0 on 2026-02-16 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_pro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageoperation',
            name='operation_type',
            field=models.CharField(choices=[('resize', 'Resize'), ('convert', 'Convert'), ('filter', 'Filter'), ('compress', 'Compress')], default='resize', max_length=20),
        ),
    ]
