# Generated by Django 6.0 on 2026-02-23 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_pro', '0002_alter_imageoperation_operation_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='is_anonymous',
        ),
    ]
