# Generated by Django 6.0 on 2026-02-28 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_pro', '0002_image_estimated_ready_at_image_processing_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='processing_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
